#!/bin/env bash

sudo curl -o /etc/yum.repos.d/security:shibboleth.repo http://download.opensuse.org/repositories/security://shibboleth/CentOS_7/security:shibboleth.repo

## this will generate files (sp-cert.pem and sp-key.pem)  in /etc/shibboleth
sudo yum install -y shibboleth

## install odbc from mysql
sudo yum localinstall -y /usr/local/tusk/extsrc/mysql/mysql-connector-odbc-5.3.9-1.el7.x86_64.rpm
sudo ln -s /usr/lib64/libmyodbc5w.so /usr/lib64/libmyodbc5.so

## Copy some shib conf files
## attribute-map.xml, shibboleth2.xml, tuskLogout.html
sudo cp /usr/local/tusk/current/install/templates/conf/shibboleth/* /etc/shibboleth

shib_dir='/usr/local/tusk/conf/etc/shibboleth'
if [ "$(ls -A $shib_dir)" ]; then
    echo "\nYou have $shib_dir and it's not empty. We assume you already have some shib setttings and we are not generating shib data files."
else
    ## modify shibboleth2.xml
    sudo sed -i 's/TUSKFQDN/$shib_domain_TUSKFQDN/' /etc/shibboleth/shibboleth2.xml
    sudo sed -i 's/SHIBFQDN/$shib_domain_SHIBFQDN/' /etc/shibboleth/shibboleth2.xml
    sudo sed -i 's/SHIBDBFQDN/$shib_domain_SHIBDBFQDN/' /etc/shibboleth/shibboleth2.xml
    sudo sed -i 's/SHIBPASSWD/$shib_domain_SHIBPASSWD/' /etc/shibboleth/shibboleth2.xml
    sudo sed -i 's/SUPPORTEMAIL/$shib_SUPPORTEMAIL/' /etc/shibboleth/shibboleth2.xml

    cd $shib_dir

    ## generate this file and put in /etc/shibboleth
    curl -o tusk-idp.xml "$shib_domain_SHIBFQDN/idp/shibboleth"
    sudo ln -s /usr/local/tusk/conf/etc/shibboleth/tusk-idp.xml /etc/shibboleth

    ## generate a metadata file and send it to the group who managges IdP so that they can set it up on their end
    curl -o tusk-metadata.xml -k "$shib_domain_TUSKFQDN/Shibboleth.sso/Metadata"
fi
