#!/bin/env bash

#######################################################
sudo chown -R tusk:tusk /usr/local/tusk

#######################################################
#### Install static custom Perl as tusk user

if -z "$git_extsrc"; then
    echo "Please provide external source in tusk_install.yml"
    exit 1
else
    cd /usr/local/tusk
    sudo -u tusk git clone $git_extsrc extsrc
fi

## add perl path
export PATH=/opt/perl/$perl_version/bin:$PATH

perl_folder="/opt/perl"
target_folder="$perl_folder/$perl_version"   ## eg /opt/perl/5.20.3
perl_source="perl-$perl_version.tar.gz"
sudo mkdir -p $target_folder
sudo chown -R tusk:tusk $perl_folder
echo "installing custom perl ..."
cd extsrc/perl
sudo -u tusk tar -xzf $perl_source

cd "perl-$perl_version"
sudo -u tusk ./Configure -des -Dprefix=$target_folder -Dusethreads -Duseshrplib
sudo -u tusk make
sudo -u tusk make test
sudo -u tusk make install

echo "completed installing perl in $target_folder"

# export PATH=$target_folder/bin:$PATH:.

### now install the rest of cpan modules
#cd /usr/local/tusk/current/install/centos
cd /opt/home/isathi01/mtusk/install/centos
sudo -u tusk curl -L http://cpanmin.us | sudo -u tusk perl - App::cpanminus

## install 2 modules from extsrc repo; make sure to install them in order
sudo -u tusk cpanm "$extsrc_folder/cpan/mod_perl-2.0.10-patch.tar.gz"
sudo -u tusk cpanm "$extsrc_folder/cpan/libapreq2-2.13-patch.tar.gz"

## install the rest of CPAN modules through cpanfile
sudo -u tusk cpanm --installdeps .

## make all modules owned by tusk user
find $target_folder \! -user tusk -exec sudo chown tusk:tusk {} \;
