#!/bin/env bash


## Set up to parse install configuration file. These variables will be global to callee scripts.
install_config_file="tusk_install.yml"

## Setup tusk/apache users
source ./create_system_accounts

## install all required yum packages
source ./install_yum_packages
## Install custom Perl and CPAN modules.
source ./install_perl
