#!/bin/sh

# Copyright 2013 Albert Einstein College of Medicine of Yeshiva University 
# 
# Licensed under the Educational Community License, Version 1.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
# 
# http://www.opensource.org/licenses/ecl1.php 
# 
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License.


. ${0%/*}/vars.sh

[ -n "$DB_HOST" ] || { echo 'DB_HOST not defined'; exit 1; }
[ -n "$DB_UID" ] || { echo 'DB_UID not defined'; exit 1; }
[ -n "$DB_PWD" ] || { echo 'DB_PWD not defined'; exit 1; }
[ -n "$DB_NAME" ] || { echo 'DB_NAME not defined'; exit 1; }
[ $# -gt 0 ] || { echo 'SQL script not specified'; exit 1; }

mysql -h $DB_HOST -u $DB_UID -p$DB_PWD $DB_NAME < $1

#
