#-----------------------------------------------------------------------------
#    mwForum - Web-based discussion forum
#    Copyright (c) 1999-2007 Markus Wichitill
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#-----------------------------------------------------------------------------

package MwfDefaults;
use strict;
use warnings;

# TUSK begin constants added
use TUSK::Constants;
# TUSK end

our ($VERSION, $options);
$VERSION = "2.11.1";

#-----------------------------------------------------------------------------
# Configuration option defaults. Don't change.

$options = [
{
	name     => 'advForumOpt',
	type     => 'checkbox',
	default  => 0,
},
{
	section  => "Email Options",
	id       => "email",
},
{
	name     => 'mailer',
	type     => 'radio',
	title    => "Email transport",
	radio    => [
		SMTP     => "Use <a href='http://en.wikipedia.org/wiki/SMTP'>SMTP</a> server",
		ESMTP    => "Use SMTP server with authentication (see FAQ.html)",
		sendmail => "Use <a href='http://www.sendmail.org/'>sendmail</a> or compatible executable (path can be set in MwfConfig.pm)",
		mail     => "Use mail/mailx executable (potentially insecure)",
	],
	default  => "$TUSK::Constants::Mailer",
},
{
	name     => 'forumEmail',
	type     => 'displaytext',
	title    => "Sender address of emails sent by forum software",
	help     => "Should be a valid address, even if nobody reads the received emails.",
	example  => [ "bounce\@example.com", "noreply\@example.com" ],
	default  => "$TUSK::Constants::ForumEmail",
},
{
	name     => 'adminEmail',
	type     => 'text',
	title    => "Main administrator's email address",
	help     => "Is displayed on the forum info page and can be obfuscated or empty if you don't want spambots to collect the address.",
	example  => [ "webmaster\@example.com", "webmaster at example company" ],
	default  => "$TUSK::Constants::ForumEmail",
},
{
	name     => 'smtpServer',
	type     => 'displaytext',
	title    => "SMTP email server host",
	help     => "Only used with SMTP mailer.",
	example  => [ "localhost", "mail.example.com" ],
	default  => "localhost",
},
{
	name     => 'esmtpAuth',
	type     => 'text',
	title    => "SMTP authentication method",
	help     => "Only used with SMTP mailer when authentication is required. See FAQ.html for details.",
	example  => [ "PLAIN", "LOGIN", "CRAM-MD5" ],
	default  => "LOGIN",
	adv      => 1,
},
{
	name     => 'esmtpUser',
	type     => 'text',
	title    => "SMTP authentication user",
	default  => "",
	adv      => 1,
},
{
	name     => 'esmtpPassword',
	type     => 'text',
	title    => "SMTP authentication password",
	default  => "",
	adv      => 1,
},
{
	name     => 'gpgSignKeyId',
	type     => 'text',
	title    => "GnuPG signing key ID",
	help     => "For optional signing/encryption of emails with GnuPG.",
	example  => [ "0x12345678", "0x1234567890ABCDEF" ],
	default  => "",
	adv      => 1,
},
{
	name     => 'gpgSignKeyPwd',
	type     => 'text',
	title    => "GnuPG signing key passphrase",
	default  => "",
	adv      => 1,
},
{
	name     => 'subscriptions',
	type     => 'checkbox',
	title    => "Enable email subscriptions of boards and topics?",
	default  => 1,
	adv      => 1,
},
{
	name     => 'noEmailReq',
	type     => 'checkbox',
	title    => "Don't require and verify email address during user registration?",
	help     => "Due to all the spam out there, forum emails will often get delayed or end up in spam folders.",
	default  => 0,
	adv      => 1,
},
{
	section  => "Global Display Options",
	id       => "globaldisp",
},
{
	name     => 'forumName',
	type     => 'displaytext',
	title    => "Name of forum",
	help     => "Try to keep this short.",
	example  => [ "Example Forum" ],
	default  => "$TUSK::Constants::ForumName",
},
{
	name     => 'homeUrl',
	type     => 'displaytext',
	title    => "URL of your homepage",
	help     => "Leave empty to disable display of home link.",
	example  => [ "http://www.example.com/" ],
	default  => "$TUSK::Constants::HomeUrl",
},
{
	name     => 'homeTitle',
	type     => 'displaytext',
	title    => "Displayed title of homepage link",
	example  => [ "Home", "Website" ],
	default  => "$TUSK::Constants::HomeTitle",
},
{
	name     => 'titleImage',
	type     => 'text',
	title    => "Title image filename",
	help     => "Leave empty if you don't need a title image.",
	example  => [ "title.png" ],
	default  => "",
},
{
	name     => 'timeFormat',
	type     => 'text',
	title    => "Time format",
	help     => "Parameters: %Y=year %m=month %d=day %H=hour %M=minute. For more parameters, see FAQ.html. The example is the ISO time format, recommended for international forums.",
	example  => [ "%Y-%m-%d %H:%M" ],
	default  => "%Y-%m-%d %H:%M",
},
{
	name     => 'boardJumpList',
	type     => 'checkbox',
	title    => "Show go-to-board dropdown list?",
	default  => 1,
},
{
	name     => 'buttonIcons',
	type     => 'checkbox',
	title    => "Show button icons on link and submit buttons?",
	help     => "Will only be shown if allowed by style and user options.",
	default  => 1,
	adv      => 1,
},
{
	name     => 'styles',
	type     => 'textarea',
	parse    => 'hash',
	title    => "Installed CSS styles",
	help     => "One Name=string pair per line. The name is what is displayed to users on their options pages, the string is used as the name of a subdirectory in the data directory and the name without extension of the CSS file.",
	example  => [ "Default=default" ],
	default  => { "Default" => "default" },
	adv      => 1,
},
{
	name     => 'styleOptions',
	type     => 'textarea',
	parse    => 'hash',
	title    => "Options for installed styles",
	help     => "See FAQ.html for details.",
	example  => [
		"Default=",
		"Default2=buttonIcons=\"1\" excludeUA=\"MSIE (?:4|5|6)\"",
	],
	default  => { "Default" => "", "Default2" => "buttonIcons=\"1\"" },
	adv      => 1,
},
{
	name     => 'styleSnippets',
	type     => 'textarea',
	parse    => 'hash',
	title    => "CSS style snippets",
	help     => "See FAQ.html for details.",
	example  => [
		"styAvaLft=div.pst img.ava { float: left; margin: 0 5px 0 0; }"
	],
	default  => {},
	adv      => 1,
},
{
	name     => 'fallbackStyle',
	type     => 'text',
	title    => "Fallback style",
	help     => "Used when the selected style isn't compatible with user's current browser. This should be a style that works with all browsers in common use, like the Default style that comes with mwForum.",
	example  => [ "Default" ],
	default  => "Default",
	adv      => 1,
},
{
	name     => 'forumStyle',
	type     => 'text',
	title    => "Additional CSS file to include",
	help     => "File goes into the data directory and is included independent of the selected style.",
	example  => [ "forum.css" ],
	default  => "",
	adv      => 1,
},
{
	section  => "Forum Page Display Options",
	id       => "forumdisp",
},
{
	name     => 'showOnlUsers',
	type     => 'radio',
	title    => "Show online users?",
	radio    => [
		0 => "No",
		1 => "Yes, show to registered users only",
		2 => "Yes, show to everybody",
	],
	default  => 0,
},
{
	name     => 'showNewUsers',
	type     => 'radio',
	title    => "Show newest users?",
	radio    => [
		0 => "No",
		1 => "Yes, show to registered users only",
		2 => "Yes, show to everybody",
	],
	default  => 0,
},
{
	name     => 'showBdayUsers',
	type     => 'radio',
	title    => "Show users that have their birthday today?",
	radio    => [
		0 => "No",
		1 => "Yes, show to registered users only",
		2 => "Yes, show to everybody",
	],
	default  => 0,
},
{
	name     => 'showNewBlgTpcs',
	type     => 'checkbox',
	title    => "Show blogs with new posts?",
	default  => 0,
},
{
	name     => 'collapseCategs',
	type     => 'text',
	title    => "Collapse board categories by default?",
	help     => "Set to 0 to disable, to the ID of a category that should stay open, or to something like 99999 to close all categories.",
	default  => 0,
	adv      => 1,
},
{
	section  => "Board Page Display Options",
	id       => "boarddisp",
},
{
	name     => 'boardPageDesc',
	type     => 'checkbox',
	title    => "Show board's long description on board page?",
	default  => 0,
},
{
	name     => 'allowTopicTags',
	type     => 'radio',
	title    => "Enable topic tags?",
	help     => "Only admins and moderators can tag other users' topics.",
	radio    => [
		0 => "No",
		1 => "Yes, enable tagging for admins and moderators",
		2 => "Yes, enable tagging for every topic poster",
	],
	default  => 0,
},
{
	name     => 'topicTags',
	type     => 'textarea',
	parse    => 'hash',
	title    => "Topic Tags",
	help     => "See FAQ.html for details.",
	example  => [ "hot=topic_hot.png Hot" ],
	default  => {},
},
{
	section  => "Topic Page Display Options",
	id       => "topicdisp",
},
{
	name     => 'showPostIp',
	type     => 'radio',
	title    => "Show IP addresses of posts?",
	radio    => [
		0 => "No",
		1 => "Yes, show to admins and moderators only",
		2 => "Yes, show to everybody",
	],
	default  => 0,
},
{
	name     => 'topicHits',
	type     => 'checkbox',
	title    => "Log and show number of times a topic is displayed?",
	default  => 0,
},
{
	name     => 'blogsFlat',
	type     => 'checkbox',
	title    => "Use non-threaded blog topics?",
	default  => 0,
},
{
	name     => 'sigStart',
	type     => 'textarea',
	title    => "String inserted before signatures",
	example  => [ "&lt;br/&gt;--&lt;br/&gt;", "&lt;/div&gt;&lt;div class='ccl sig'&gt;" ],
	default  => "\n</div>\n<div class='ccl sig'>\n",
	adv      => 1,
},
{
	name     => 'sigEnd',
	type     => 'textarea',
	title    => "String inserted after signatures",
	default  => "",
	adv      => 1,
},
{
	section  => "User Display Options",
	id       => "userdisp",
},
{
	name     => 'showUserIp',
	type     => 'checkbox',
	title    => "Show user's last used IP on user info page to everybody?",
	default  => 0,
},
{
	name     => 'boardAdminAmp',
	type     => 'checkbox',
	title    => "Prefix \@ to names of moderators in topics of their boards?",
	help     => "For performance reasons, doesn't work for users who have moderator status by way of group membership.",
	default  => 1,
	adv      => 1,
},
{
	name     => 'anonName',
	type     => 'text',
	title    => "String to use as username for anonymous posts",
	help     => "Special string 'ip' inserts IP address as name.",
	example  => [ "Anonymous Coward" ],
	default  => "anonymous",
},
{
	name     => 'userTitles',
	type     => 'textarea',
	parse    => 'array',
	title    => "User Titles",
	help     => "See FAQ.html for details.",
	example  => [ "Admin", "Moderator" ],
	default  => [],
},
{
	name     => 'userRanks',
	type     => 'textarea',
	parse    => 'array',
	title    => "User Ranks",
	help     => "See FAQ.html for details.",
	default  => [],
},
{
	name     => 'geoIp',
	type     => 'text',
	title    => "Enable GeoIP (country of user's IP address) lookup?",
	help     => "Set to GeoIP.dat file location to enable. See FAQ.html for details.",
	example  => [ "/usr/local/share/GeoIP/GeoIP.dat" ],
	default  => "",
	adv      => 1,
},
{
	name     => 'geoIpSkip',
	type     => 'text',
	title    => "Don't show GeoIP flags for this country code",
	help     => "You can use this if the majority of your users comes from a single country and only the rest should be highlighted.",
	example  => [ "us" ],
	default  => "",
	adv      => 1,
},
{
	section  => "Internationalization Options",
	id       => "i18n",
},
{
	name     => 'charset',
	type     => 'text',
	title    => "Character set",
	example  => [ "iso-8859-1" ],
	default  => "iso-8859-1",
},
{
	name     => 'languages',
	type     => 'textarea',
	parse    => 'hash',
	title    => "Installed language modules",
	help     => "One Language=Module pair per line. All of these modules must use the character set specified above. Don't delete the MwfEnglish.pm file, even if you don't enable it here. Get rid of German if you don't need it.",
	example  => [ "English=MwfEnglish" ],
	default  => { "English" => "MwfEnglish", "German" => "MwfGerman" },
},
{
	name     => 'languageCodes',
	type     => 'textarea',
	parse    => 'hash',
	title    => "Language code to language name mapping ",
	help     => "One code=Language pair per line. Code must be in lowercase. Used for automatic language selection by HTTP <a href='http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4'>Accept-Language</a> header for new users and guests.",
	example  => [ "en=English" ],
	default  => { "en" => "English", "de" => "German" },
	adv      => 1,
},
{
	name     => 'win1252',
	type     => 'radio',
	title    => "Handling of Windows-125x characters that are not valid in ISO-8859 codepages",
	help     => "The second option can be used in forums for Windows users only and might be necessary for forums with non-ISO-8859-based codepages. No filtering is done in UTF-8 mode.",
	radio    => [
		0 => "Replace with similar ASCII characters/strings",
		1 => "Don't touch, pass transparently",
		2 => "Remove completely",
	],
	default  => 0,
},
{
	section  => "Avatar Options",
	id       => "avatar",
},
{
	name     => 'avatars',
	type     => 'checkbox',
	title    => "Enable avatar images?",
	help     => "See FAQ.html for details before enabling.",
	default  => 1,
},
{
	name     => 'avatarUpload',
	type     => 'checkbox',
	title    => "Enable avatar upload?",
	default  => 1,
},
{
	name     => 'avatarGallery',
	type     => 'checkbox',
	title    => "Enable avatar gallery?",
	default  => 1,
},
{
	name     => 'avatarResize',
	type     => 'checkbox',
	title    => "Automatically reformat avatars that don't conform to restrictions?",
	default  => 0,
},
{
	name     => 'avatarMaxSize',
	type     => 'text',
	title    => "Max. filesize of avatar images in bytes",
	default  => 50000,
	adv      => 1,
},
{
	name     => 'avatarWidth',
	type     => 'text',
	title    => "Exact width of avatar images in pixels",
	help     => "Since the same number must be used in stylesheets, it's best not to change the default value of 50. See FAQ.html for details.",
	default  => 100,
	adv      => 1,
},
{
	name     => 'avatarHeight',
	type     => 'text',
	title    => "Exact height of avatar images in pixels",
	default  => 100,
	adv      => 1,
},
{
	section  => "Quoting Options",
	id       => "quote",
	adv      => 1,
},
{
	name     => 'quote',
	type     => 'radio',
	title    => "Enable auto-quoting of posts and messages in replies?",
	help     => "Auto-quoting will often turn topics into deserts consisting of mostly quotes and very little new text, while eating lots of precious RAM. NOT recommended, just use manual copy&amp;paste quoting instead. See FAQ.html for details.",
	radio    => [
		0 => "No",
		1 => "Yes, in non-threaded topics",
		2 => "Yes, in threaded topics, too (doesn't work well because of the often narrow posts)",
	],
	default  => 0,
	adv      => 1,
},
{
	name     => 'quotePrefix',
	type     => 'checkbox',
	title    => "Prefix 'username:' to quotes?",
	default  => 0,
	adv      => 1,
},
{
	name     => 'quoteCols',
	type     => 'text',
	title    => "Width of quoted text in characters",
	default  => 60,
	adv      => 1,
},
{
	section  => "Markup Options",
	id       => "markup",
},
{
	name     => 'smileys',
	type     => 'checkbox',
	title    => "Display smileys :) ;) :( :O as images?",
	default  => 1,
},
{
	name     => 'imgTag',
	type     => 'checkbox',
	title    => "Enable [img] markup tag?",
	help     => "Potential security risk. Also, don't enable for forums that support or require <a href='http://en.wikipedia.org/wiki/Secure_Sockets_Layer'>SSL</a> to avoid mixed-content-warning-popups.",
	default  => 0,
},
{
	name     => 'tags',
	type     => 'textarea',
	parse    => 'hash',
	title    => "Replace :tags: in colons with text or (X)HTML",
	help     => "One tag=text pair per line. Can be used for additional smileys etc.",
	example  => [ "readfaq=&lt;img src='/mwf/tag_readfaq.png' alt='Read the FAQ'/&gt;" ],
	default  => {},
},
{
	name     => 'tagButtons',
	type     => 'radio',
	title    => "Show insert buttons for tags?",
	radio    => [
		0 => "No",
		1 => "Yes, show buttons for [tags]",
		2 => "Yes, show buttons for [tags] and :tags:",
	],
	default  => 0,
},
{
	name     => 'fullSigs',
	type     => 'checkbox',
	title    => "Allow full signatures with markup and no size limit?",
	help     => "Otherwise only classic signatures with max. 100 characters on two lines are allowed.",
	default  => 0,
},
{
	section  => "Attachment Options",
	id       => "attach",
},
{
	name     => 'attachUrlPath',
	type     => 'displaytext',
	title    => "URL path of attachments",
	help     => "This must not be a subpath of the script path, or HTML attachments will be able to steal login cookies.",
	example  => [ "/mwf/attach" ],
	default  => "$TUSK::Constants::AttachUrlPath",
},
{
	name     => 'attachments',
	type     => 'checkbox',
	title    => "Enable file attachments?",
	help     => "Don't enable unless you are sure that uploaded files can't be executed on the server. You also need to set the attachFsPath option in MwfConfig.pm and enable attachments per board.",
	default  => 1,
},
{
	name     => 'attachImg',
	type     => 'checkbox',
	title    => "Enable embedded display of attached images?",
	help     => "Embedded images will use up a whole lot more bandwidth than non-embedded images.",
	default  => 1,
},
{
	name     => 'attachImgThb',
	type     => 'checkbox',
	title    => "Force all embedded attached images above a certain size to be displayed as thumbnails?",
	help     => "Requires GD and Image::Info, or Image::Magick Perl modules. Can save a lot of bandwidth.",
	default  => 1,
},
{
	name     => 'attachList',
	type     => 'radio',
	title    => "Enable the attachment list page?",
	radio    => [
		0 => "No",
		3 => "Yes, visible for admins only",
		2 => "Yes, visible for registered users only",
		1 => "Yes, visible for everybody",
	],
	default  => 0,
},
{
	name     => 'attachGallery',
	type     => 'checkbox',
	title    => "Enable image gallery mode of attachment list?",
	help     => "Requires GD and Image::Info, or Image::Magick Perl modules.",
	default  => 0,
},
{
	section  => "Chat Options",
	id       => "chat",
	adv      => 1,
},
{
	name     => 'chat',
	type     => 'radio',
	title    => "Enable chat page?",
	radio    => [
		0 => "No",
		2 => "Yes, visible for registered users only",
		1 => "Yes, visible for everybody",
	],
	default  => 0,
	adv      => 0,
},
{
	name     => 'chatMaxLength',
	type     => 'text',
	title    => "Max. chat message length",
	default  => 400,
	adv      => 1,
},
{
	name     => 'chatMaxMsgs',
	type     => 'text',
	title    => "Max. number of chat messages displayed",
	default  => 25,
	adv      => 1,
},
{
	name     => 'chatMaxAge',
	type     => 'text',
	title    => "Expire old chat messages after x days",
	default  => 1,
	adv      => 1,
},
{
	section  => "Cronjob Options",
	id       => "cron",
},
{
	name     => 'scriptUrlPath',
	type     => 'displaytext',
	title    => "URL path to script directory (no trailing /)",
	help     => "The <a href='http://www.unixgeeks.org/security/newbie/unix/cron-1.html'>cronjobs</a> need to get the path from this option, since they can't get it from the webserver.",
	example  => [ "/cgi-bin/mwf" ],
	default  => "$TUSK::Constants::ScriptUrlPath",
},
{
	name     => 'acctExpiration',
	type     => 'text',
	title    => "Expire user accounts that have never been used after x days",
	help     => "0 = never",
	default  => 0,
},
{
	name     => 'userExpiration',
	type     => 'text',
	title    => "Expire user accounts after x days of absence",
	help     => "0 = never",
	default  => 0,
},
{
	name     => 'noUserPostsExp',
	type     => 'checkbox',
	title    => "But never expire user accounts with existing posts?",
	default  => 0,
	adv      => 1,
},
{
	name     => 'bdayExpiration',
	type     => 'text',
	title    => "Expire birthdays after x days of absence",
	help     => "0 = never",
	default  => 0,
	adv      => 1,
},
{
	name     => 'subsExpiration',
	type     => 'text',
	title    => "Expire board and topic subscriptions after x days of absence",
	help     => "0 = never",
	default  => 0,
	adv      => 1,
},
{
	name     => 'msgExpiration',
	type     => 'text',
	title    => "Expire private messages after x days",
	help     => "0 = never",
	default  => 0,
},
{
	name     => 'blogExpiration',
	type     => 'text',
	title    => "Expire inactive blog topics after x days",
	help     => "0 = never",
	default  => 0,
},
{
	name     => 'hugeTpcLocking',
	type     => 'text',
	title    => "Lock topics with more than x posts",
	help     => "0 = don't. Huge topics drain a lot of performance and RAM due to their threaded nature.",
	default  => 0,
	adv      => 1,
},
{
	name     => 'pollLockTime',
	type     => 'text',
	title    => "Close polls x days after topic creation",
	help     => "0 = never",
	default  => 0,
	adv      => 1,
},
{
	name     => 'pollLocking',
	type     => 'checkbox',
	title    => "Close polls in locked topics?",
	default  => 0,
	adv      => 1,
},
{
	name     => 'cronEmu',
	type     => 'checkbox',
	title    => "Enable cron emulation?",
	help     => "If no cron daemon/task scheduler is available, this will start the cron_jobs.pl script on the first request of every day. Only use in small forums, script might get killed by timeout otherwise.",
	default  => 0,
},
{
	section  => "Default User Options",
	id       => "user",
},
{
	name     => 'hideEmail',
	type     => 'checkbox',
	title    => "Hide email address?",
	default  => 1,
},
{
	name     => 'privacy',
	type     => 'checkbox',
	title    => "Hide online status?",
	default  => 0,
},
{
	name     => 'tempLogin',
	type     => 'checkbox',
	title    => "Unchecked login remember-me checkbox by default?",
	default  => 0,
	adv      => 1,
},
{
	name     => 'secureLogin',
	type     => 'checkbox',
	title    => "Limit login cookies to SSL connections?",
	default  => 0,
	adv      => 1,
},
{
	name     => 'notify',
	type     => 'checkbox',
	title    => "Receive notifications of replies to posts?",
	default  => 1,
},
{
	name     => 'msgNotify',
	type     => 'checkbox',
	title    => "Receive post reply and message notifications by email, too?",
	default  => 1
},
{
	name     => 'userTimezone',
	type     => 'text',
	title    => "Timezone",
	help     => "Number relative to GMT from -14 to +14 in .5 increments.",
	default  => '-5',
},
{
	name     => 'language',
	type     => 'text',
	title    => "User interface language",
	example  => [ "English" ],
	default  => "English",
},
{
	name     => 'style',
	type     => 'text',
	title    => "CSS style",
	example  => [ "Default" ],
	default  => "Default2",
},
{
	name     => 'fontFace',
	type     => 'text',
	title    => "Font face",
	example  => [ "Verdana" ],
	default  => "Verdana",
},
{
	name     => 'fontSize',
	type     => 'text',
	title    => "Font size in pixels",
	help     => "0 = use browser's default size.",
	default  => 0,
},
{
	name     => 'boardDescs',
	type     => 'checkbox',
	title    => "Show board descriptions?",
	default  => 1,
},
{
	name     => 'showDeco',
	type     => 'checkbox',
	title    => "Show decorations like user titles, ranks, smileys and topic tags?",
	default  => 1,
},
{
	name     => 'showAvatars',
	type     => 'checkbox',
	title    => "Show avatars?",
	default  => 1,
},
{
	name     => 'showImages',
	type     => 'checkbox',
	title    => "Show embedded images?",
	default  => 1,
},
{
	name     => 'showSigs',
	type     => 'checkbox',
	title    => "Show signatures?",
	default  => 1,
},
{
	name     => 'collapse',
	type     => 'checkbox',
	title    => "Auto-collapse topic branches without new/unread posts?",
	default  => 0,
},
{
	name     => 'indent',
	type     => 'text',
	title    => "Threading indent in percent",
	default  => 3,
},
{
	name     => 'topicsPP',
	type     => 'text',
	title    => "Topics per board page",
	default  => 25,
},
{
	name     => 'postsPP',
	type     => 'text',
	title    => "Posts per topic page",
	default  => 50,
},
{
	section  => "Custom User Profile Options",
	id       => "profile",
	adv      => 1,
},
{
	name     => 'extra1',
	type     => 'text',
	title    => "Short custom field 1 label on user info page",
	help     => "Leave empty to not use custom field.",
	example  => [ "Reg. Name", "Reg. Code" ],
	default  => "",
	adv      => 1,
},
{
	name     => 'extra2',
	type     => 'text',
	title    => "Short custom field 2 label on user info page",
	default  => "",
	adv      => 1,
},
{
	name     => 'extra3',
	type     => 'text',
	title    => "Short custom field 3 label on user info page",
	default  => "",
	adv      => 1,
},
{
	name     => 'longExtra1',
	type     => 'text',
	title    => "Long custom field 1 label on user options/registration pages",
	example  => [ "Shareware registration name", "Shareware registration code" ],
	default  => "",
	adv      => 1,
},
{
	name     => 'longExtra2',
	type     => 'text',
	title    => "Long custom field 2 label on user options/registration pages",
	default  => "",
	adv      => 1,
},
{
	name     => 'longExtra3',
	type     => 'text',
	title    => "Long custom field 3 label on user options/registration pages",
	default  => "",
	adv      => 1,
},
{
	name     => 'showExtra1',
	type     => 'checkbox',
	title    => "Show custom field 1 on user info page to everybody?",
	default  => 0,
	adv      => 1,
},
{
	name     => 'showExtra2',
	type     => 'checkbox',
	title    => "Show custom field 2 on user info page to everybody?",
	default  => 0,
	adv      => 1,
},
{
	name     => 'showExtra3',
	type     => 'checkbox',
	title    => "Show custom field 3 on user info page to everybody?",
	default  => 0,
	adv      => 1,
},
{
	name     => 'regExtra1',
	type     => 'radio',
	title    => "Show editable custom field 1 on which page?",
	radio    => [
		0 => "Only on user options page",
		1 => "On both pages",
		2 => "Only on registration page",
	],
	default  => 0,
	adv      => 1,
},
{
	name     => 'regExtra2',
	type     => 'radio',
	title    => "Show editable custom field 2 on which page?",
	radio    => [
		0 => "Only on user options page",
		1 => "On both pages",
		2 => "Only on registration page",
	],
	default  => 0,
	adv      => 1,
},
{
	name     => 'regExtra3',
	type     => 'radio',
	title    => "Show editable custom field 3 on which page?",
	radio    => [
		0 => "Only on user options page",
		1 => "On both pages",
		2 => "Only on registration page",
	],
	default  => 0,
	adv      => 1,
},
{
	section  => "Bounced Email Options",
	id       => "bounce",
	adv      => 1,
},
{
	name     => 'bounceTrshWarn',
	type     => 'text',
	title    => "Add a notification message for user if he has at least x bounces",
	help     => "0 = never",
	default  => 0,
	adv      => 1,
},
{
	name     => 'bounceTrshCncl',
	type     => 'text',
	title    => "Cancel subscriptions/notifications if user has x bounces",
	help     => "0 = never",
	default  => 0,
	adv      => 1,
},
{
	name     => 'bounceTrshDsbl',
	type     => 'text',
	title    => "Disable all email to user if user has x bounces",
	help     => "0 = never",
	default  => 0,
	adv      => 1,
},
{
	name     => 'bouncePopHost',
	type     => 'text',
	title    => "POP3 account host",
	default  => "localhost",
	adv      => 1,
},
{
	name     => 'bouncePopUser',
	type     => 'text',
	title    => "POP3 account username",
	default  => "",
	adv      => 1,
},
{
	name     => 'bouncePopPwd',
	type     => 'text',
	title    => "POP3 account password",
	default  => "",
	adv      => 1,
},
{
	name     => 'bouncePopAuth',
	type     => 'text',
	title    => "POP3 authentication method",
	example  => [ "PASS", "APOP", "CRAM-MD5" ],
	default  => "PASS",
	adv      => 1,
},
{
	name     => 'bouncePopPort',
	type     => 'text',
	title    => "POP3 port number",
	default  => "",
	adv      => 1,
},
{
	name     => 'bouncePopTout',
	type     => 'text',
	title    => "POP3 timeout in seconds",
	default  => "",
	adv      => 1,
},
{
	name     => 'bouncePopSsl',
	type     => 'checkbox',
	title    => "Enable POP3 via SSL",
	help     => "See FAQ.html for details.",
	default  => 0,
	adv      => 1,
},
{
	name     => 'bouncePopDbg',
	type     => 'checkbox',
	title    => "Enable POP3 debug log",
	default  => 0,
	adv      => 1,
},
{
	section  => "Feed Options",
	id       => "feed",
	adv      => 1,
},
{
	name     => 'rssLink',
	type     => 'checkbox',
	title    => "Generate Atom and RSS feeds and enable link to feeds page?",
	help     => "See FAQ.html for details. Requires attachment directory and cron_rss.pl cronjob.",
	default  => 0,
	adv      => 1,
},
{
	name     => 'microsummary',
	type     => 'checkbox',
	title    => "Generate and advertise microsummary containing last post time?",
	help     => "Can be used for Firefox <a href='http://www.mozilla.com/en-US/firefox/features.html#livetitles'>Live Titles</a>. Requires attachment directory and cron_rss.pl cronjob.",
	default  => 0,
	adv      => 1,
},
{
	name     => 'rssDesc',
	type     => 'text',
	title    => "Feed description",
	default  => "Latest forum posts",
	adv      => 1,
},
{
	name     => 'rssItems',
	type     => 'text',
	title    => "Number of posts in feeds",
	default  => 15,
	adv      => 1,
},
{
	name     => 'rssExclude',
	type     => 'text',
	title    => "Comma-separated list of board IDs to exclude from global feed",
	help     => "0 = none. Use for test and unimportant boards etc.",
	example  => [ "3,5,7" ],
	default  => "0",
	adv      => 1,
},
{
	section  => "Cookie Options",
	id       => "cookie",
},
{
	name     => 'cookiePrefix',
	type     => 'text',
	title    => "Cookie prefix string used for unique cookie names",
	help     => "Only needs to be modified if you are using multiple forums where one script path is a substring of another (e.g. /cgi-bin/mwf and /cgi-bin/mwf2) or when you change the <a href='http://wp.netscape.com/newsref/std/cookie_spec.html'>cookie</a> domain and/or path.",
	example  => [ "mwf_" ],
	default  => "mwf_",
},
{
	name     => 'cookieDomain',
	type     => 'text',
	title    => "Cookie domain override",
	help     => "If your site is available at http://example.com and http://www.example.com then set cookieDomain to 'example.com' to allow login cookies to work with either hostname. If you change this in an established forum, also change the cookie prefix string.",
	example  => [ "example.com" ],
	default  => "",
},
{
	name     => 'cookiePath',
	type     => 'text',
	title    => "Cookie path override",
	help     => "The attachment URL path must never be a subpath of the cookie path or HTML attachments will be able to steal login cookies. If you change this in an established forum, also change the cookie prefix string.",
	example  => [ "/" ],
	default  => "",
},
{
	name     => 'enableSecLogin',
	type     => 'checkbox',
	title    => "Allow users to limit their login cookies to SSL connections?",
	help     => "Only enable if server has SSL and users are smart enough not to lock themselves out.",
	default  => 0,
	adv      => 1,
},
{
	section  => "Search Options",
	id       => "search",
	adv      => 1,
},
{
	name     => 'forumSearch',
	type     => 'checkbox',
	title    => "Enable forum search feature?",
	help     => "Searching is an important feature, but can sometimes overtax a busy server.",
	default  => 1,
	adv      => 1,
},
{
	name     => 'advSearch',
	type     => 'checkbox',
	title    => "Enable indexed search mode?",
	help     => "See FAQ.html for details.",
	default  => 0,
	adv      => 1,
},
{
	name     => 'logSearchWords',
	type     => 'checkbox',
	title    => "Enable search string logging?",
	help     => "Search strings are stored in the logStrings table.",
	default  => 0,
	adv      => 1,
},
{
	name     => 'showAdvOpt',
	type     => 'checkbox',
	title    => "Always show advanced search options?",
	default  => 0,
	adv      => 1,
},
{
	name     => 'showSearchBody',
	type     => 'checkbox',
	title    => "Show post bodies in search results by default?",
	default  => 0,
	adv      => 1,
},
{
	section  => "Restriction Options",
	id       => "restrict",
	adv      => 1,
},
{
	name     => 'maxUserNameLen',
	type     => 'text',
	title    => "Max. length of usernames",
	default  => 15,
	adv      => 1,
},
{
	name     => 'reservedNames',
	type     => 'textarea',
	parse    => 'array',
	title    => "Reserved usernames that cannot be registered",
	help     => "One username per line. Entries use simple substring matching, i.e. 'admin' will also prevent registrations with names like 'the_administrator'.",
	default  => [],
	adv      => 1,
},
{
	name     => 'userNameRegExp',
	type     => 'text',
	title    => "Regular expression that defines a valid username",
	help     => "May have to be changed for non-latin languages. Just letting the user use arbitrary chars is a security risk however. Additional restrictions apply, see user_register for details.",
	example  => [ "^[\\w\\.\\- ]+\$", "^[A-Za-z0-9\\.\\- ]+\$" ],
	default  => "^[\\w\\.\\- ]+\$",
	adv      => 1,
},
{
	name     => 'emailRegExp',
	type     => 'text',
	title    => "Regular expression that defines a valid email address",
	example  => [ "^[\\w\\.\\-\\+]+?\\\@(?:[\\w\\-]+\\.)+\\w{2,}\$" ],
	default  => "^[\\w\\.\\-\\+]+?\\\@(?:[\\w\\-]+\\.)+\\w{2,}\$",
	adv      => 1,
},
{
	name     => 'maxSubjectLen',
	type     => 'text',
	title    => "Max. topic subject length",
	default  => 60,
	adv      => 1,
},
{
	name     => 'maxBodyLen',
	type     => 'text',
	title    => "Max. post and message body length",
	default  => 16000,
	adv      => 1,
},
{
	name     => 'maxListUsers',
	type     => 'text',
	title    => "Max. number of usernames in listboxes",
	default  => 250,
	adv      => 1,
},
{
	name     => 'minRegTime',
	type     => 'text',
	title    => "Users must be registered for a least x seconds before they can post",
	default  => 0,
	adv      => 1,
},
{
	name     => 'repostTime',
	type     => 'text',
	title    => "Users must pause x seconds between posts/messages",
	default  => 0,
	adv      => 1,
},
{
	name     => 'postEditTime',
	type     => 'text',
	title    => "Limit editing of posts to x seconds after posting",
	help     => "0 = don't limit",
	default  => 0,
	adv      => 1,
},
{
	name     => 'sessionTimeout',
	type     => 'text',
	title    => "Sessions time out after x minutes",
	default  => 30,
	adv      => 1,
},
{
	name     => 'hostnameBlocks',
	type     => 'textarea',
	parse    => 'array',
	title    => "Email address hostname blocking",
	help     => "One hostname per line.",
	example  => [ "example.com" ],
	default  => [],
	adv      => 1,
},
{
	name     => 'ipBlocks',
	type     => 'textarea',
	parse    => 'array',
	title    => "IP blocking",
	help     => "One IP address per line. Webserver access control features are much faster, but not always available.",
	example  => [ "123.123.123." ],
	default  => [],
	adv      => 1,
},
{
	name     => 'censorWords',
	type     => 'textarea',
	parse    => 'array',
	title    => "Censor words, replace with asterisks",
	help     => "One word per line. This feature is easily fooled, don't expect too much of it.",
	default  => [],
	adv      => 1,
},
{
	name     => 'banViewing',
	type     => 'checkbox',
	title    => "Deny read access to banned users?",
	help     => "Otherwise they can still read but not post, edit etc.",
	default  => 0,
	adv      => 1,
},
{
	name     => 'locked',
	type     => 'checkbox',
	title    => "Lock forum for everybody except admins?",
	default  => 0,
	adv      => 1,
},
{
	name     => 'adminUserReg',
	type     => 'checkbox',
	title    => "Hide user registration page and allow registration only by admins?",
	default  => 0,
	adv      => 1,
},
{
	name     => 'captcha',
	type     => 'radio',
	title    => "Use captchas to keep out spambots?",
	help     => "If you want to use <a href='http://en.wikipedia.org/wiki/CAPTCHA'>captcha</a> images, you have to fill out the font option below, otherwise cheap pseudo-captchas will be used (which are easy to circumvent, although most spambots won't).",
	radio    => [
		0 => "No",
		1 => "Yes, use for user registrations",
		2 => "Yes, use for user registrations and anonymous posts",
		3 => "Yes, use for user registrations and all posts and private messages",
	],
	default  => 0,
	adv      => 1,
},
{
	name     => 'captchaFont',
	type     => 'text',
	title    => "Full path to a TTF font file for captcha images",
	help     => "Captcha images require the GD (with TTF support) and GD::SecurityImage, or Image::Magick (with TTF support) and GD::SecurityImage Perl modules. Also required is a writable attachment directory as per the File Attachments instructions in FAQ.html.",
	example  => [ "/usr/local/share/ttf/captcha.ttf" ],
	default  => "",
	adv      => 1,
},
{
	section  => "Performance Options",
	id       => "perform",
	adv      => 1,
},
{
	name     => 'maxTopicsPP',
	type     => 'text',
	title    => "Max. number of topics per board page",
	default  => 100,
	adv      => 1,
},
{
	name     => 'maxPostsPP',
	type     => 'text',
	title    => "Max. number of posts per page",
	default  => 200,
	adv      => 1,
},
{
	name     => 'maxUnreadDays',
	type     => 'text',
	title    => "Treat posts as read after x days",
	default  => 7,
	adv      => 1,
},
{
	name     => 'skipNewComp',
	type     => 'checkbox',
	title    => "Disable computation of new post numbers on main forum page?",
	help     => "Disable for better forum page performance in huge forums.",
	default  => 0,
	adv      => 1,
},
{
	name     => 'skipUnreadComp',
	type     => 'checkbox',
	title    => "Disable computation of read checkmarks on main forum page?",
	help     => "Disable for better forum page performance in huge forums.",
	default  => 0,
	adv      => 1,
},
{
	name     => 'skipStickySort',
	type     => 'checkbox',
	title    => "Disable topic sorting by stickyness?",
	help     => "Disable for better board page performance in forums with thousands of topics, especially with InnoDB or PostgreSQL. Sticky topics won't be at the top anymore, but they're still in bold.",
	default  => 0,
	adv      => 1,
},
{
	section  => "Misc. Feature Options",
	id       => "misc",
},
{
	name     => 'messages',
	type     => 'checkbox',
	title    => "Enable private messages?",
	default  => 1,
},
{
	name     => 'polls',
	type     => 'radio',
	title    => "Enable polls?",
	help     => "Only admins and moderators can add polls to other users' topics.",
	radio    => [
		0 => "No",
		2 => "Yes, enable poll creation for admins and moderators only",
		1 => "Yes, enable poll creation for all users",
	],
	default  => 1,
},
{
	name     => 'blogs',
	type     => 'radio',
	title    => "Enable user blogs?",
	help     => "Blogs in mwForum are personal boards for every user, with the owner being moderator and the only one who can start new topics.",
	radio    => [
		0 => "No",
		2 => "Yes, visible for registered users only",
		1 => "Yes, visible for everybody",
	],
	default  => 0,
},
{
	name     => 'userList',
	type     => 'radio',
	title    => "Enable user list?",
	help     => "This is not the same user list as the one used by admins.",
	radio    => [
		0 => "No",
		2 => "Yes, visible for registered users only",
		1 => "Yes, visible for everybody",
	],
	default  => 0,
},
{
	name     => 'noteDefMod',
	type     => 'checkbox',
	title    => "Enable the 'Notify user' checkbox for moderator actions by default?",
	default  => 0,
	adv      => 1,
},
{
	name     => 'noCacheHeaders',
	type     => 'checkbox',
	title    => "Enable 'Pragma/Cache-Control: no-cache' headers?",
	help     => "Otherwise, only '<a href='http://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html#sec13.1.3'>Cache-Control: private</a>' is sent, which some old cache proxies ignore, resulting in users getting other users' cached pages sometimes, if they use the same cache proxy (e.g. AOL).",
	default  => 0,
	adv      => 1,
},
{
	name     => 'noIndex',
	type     => 'checkbox',
	title    => "Enable 'Robots: noindex,nofollow' meta tag?",
	help     => "Tells robots not to index this forum, should using <a href='http://www.robotstxt.org/wc/robots.html'>robots.txt</a> be impossible.",
	default  => 0,
	adv      => 1,
},
{
	name     => 'trashBoardId',
	type     => 'text',
	title    => "Board ID of a board to be used as a trash bin for manually deleted topics",
	help     => "0 = none",
	default  => 0,
	adv      => 1,
},
{
	name     => 'policyTitle',
	type     => 'text',
	title    => "Forum policy title",
	example  => [ "Forum ToS" ],
	default  => "",
},
{
	name     => 'policy',
	type     => 'textarea',
	title    => "Forum policy",
	help     => "Can contain greeting/intro text, conduct rules, etc. This text is sent in registration emails and displayed on the forum info page. Don't use HTML.",
	example  => [ "Welcome to the forum! Please follow these simple rules: blah blah ..." ],
	default  => "",
},
{
	section  => "Expert Options",
	id       => "exp",
	adv      => 1,
},
{
	name     => 'xhtml',
	type     => 'checkbox',
	title    => "Send real XHTML (application/xhtml+xml) to browsers that accept it?",
	help     => "Only use if all your custom markup (included via options, language modules, include plugins, code modifications etc.) is well-formed <a href='http://www.w3.org/TR/REC-xml'>XML</a> and valid <a href='http://www.w3.org/TR/xhtml11'>XHTML 1.1</a>.",
	default  => 0,
	adv      => 1,
},
{
	name     => 'logLevel',
	type     => 'radio',
	title    => "Enable event logging?",
	help     => "The log data is only available from the database, so leave this off unless you speak SQL.",
	radio    => [
		0 => "No",
		1 => "Level 1 - Log important events only (those that usually modify the database)",
		2 => "Level 2 - Also log important page views (forum, board, topic, search)",
		3 => "Level 3 - Also log less important page views",
	],
	default  => 0,
	adv      => 1,
},
{
	name     => 'debug',
	type     => 'radio',
	title    => "Show debug messages?",
	radio    => [
		0 => "No",
		1 => "Level 1 - Warn about text not in <a href='http://www.unicode.org/reports/tr15/'>Unicode NFC/NFKC</a>",
		2 => "Level 2 - Also print all SQL queries",
	],
	default  => 0,
	adv      => 1,
},
{
	name     => 'dataBaseUrl',
	type     => 'text',
	title    => "Data base URL",
	help     => "All images, CSS files and attachments can be served from a different base URL for load balancing and/or attachment security purposes.",
	example  => [ "http://data.example.org:81" ],
	default  => "",
	adv      => 1,
},
{
	name     => 'relRedir',
	type     => 'checkbox',
	title    => "Use relative Location headers for redirection?",
	help     => "Violates the HTTP spec, but usually works fine and solves problems with some advanced setups involving SSL and front/backend webservers.",
	default  => 0,
	adv      => 1,
},
{
	section  => "Plugin Options",
	id       => "plugin",
	adv      => 1,
},
{
	name     => 'includePlg',
	type     => 'textarea',
	parse    => 'hash',
	title    => "Include Plugins",
	help     => "One name=function pair per line.",
	example  => [ "top=MwfPlgExample::printAds" ],
	default  => {
		httpHeader => "",
		htmlHeader => "",
		top => "MwfPlgInclude::top",
		middle => "MwfPlgInclude::middle",
		bottom => "MwfPlgInclude::bottom",
	},
	adv      => 1,
},
{
	name     => 'authenPlg',
	type     => 'textarea',
	parse    => 'hash',
	title    => "Authentication Plugins",
	help     => "One name=function pair.",
	example  => [ "request=MwfPlgExample::authenRequest" ],
	default  => { 
		login => "",
		request => "MwfPlgAuthen::authenRequestHttp",
	},
	adv      => 1,
},
{
	name     => 'authzPlg',
	type     => 'textarea',
	parse    => 'hash',
	title    => "Authorization Plugins",
	help     => "One name=function pair per line.",
	example  => [ "viewBoard=MwfPlgExample::viewBoard" ],
	default  => {
		regUser => "",
		userOpt => "",
		viewBoard => "MwfPlgAuthz::viewBoard",
		newTopic => "",
		newPost => "",
		editPost => "",
		attach => "",
		deletePost => "",
	},
	adv      => 1,
},
{
	name     => 'logPlg',
	type     => 'textarea',
	parse    => 'array',
	title    => "Log/Event Plugins",
	help     => "One plugin function per line.",
	example  => [ "MwfPlgExample::log" ],
	default  => [],
	adv      => 1,
},
{
	name     => 'msgDisplayPlg',
	type     => 'textarea',
	title    => "Message Display Plugins",
	help     => "One plugin function.",
	example  => [ "MwfPlgExample::moreSmileys" ],
	default  => "",
	adv      => 1,
},
];

#------------------------------------------------------------------------------

# Load local additions
do 'MwfDefaultsLocal.pm';

#-----------------------------------------------------------------------------
# Return OK
1;
