#!/usr/bin/perl -w
# makezip: takes everything in the folder, and makes a zip file out of it
# $Revision: 1.1 $, $Date: 2001-08-06 21:07:14 $
use File::Find;
my @f = ();
$w = sub { -f && $_ !~ /CVS/  && $_ !~ /~$/ && push @f, $_ };
find ({ wanted => $w, no_chdir => 1 }, '.');
exec 'zip', '-r', 'hscml', @f;
