USE hsdb4;

ALTER table hsdb4.user 
CHANGE uid uid int(10) NOT NULL after user_id,
CHANGE firstname firstname varchar(20) CHARACTER SET utf8 NOT NULL DEFAULT '' after uid,
CHANGE midname midname varchar(20) CHARACTER SET utf8 DEFAULT NULL after firstname,
CHANGE lastname lastname varchar(40) CHARACTER SET utf8 NOT NULL DEFAULT '' after midname,
CHANGE suffix suffix varchar(10) CHARACTER SET utf8 DEFAULT NULL after lastname,
CHANGE loggedout_flag loggedout_flag int(1) unsigned DEFAULT '1' after previous_login,
CHANGE password_reset password_reset datetime DEFAULT NULL after password,
ADD source_enum_id int(10) unsigned NULL after source
;

USE tusk;

ALTER table enum_data 
CHANGE description description varchar(200) NOT NULL DEFAULT '' after short_name,
ADD display tinyint(1) UNSIGNED default 0 after description
;

INSERT INTO enum_data VALUES
(0, 'user.source_id', 'internal', 'Internal', 1, 'Manually and internally maintained', 'script', now()),
(0, 'user.source_id', 'external', 'Authentication', 1, 'Externally maintained eg LDAP', 'script', now()),
(0, 'user.source_id', 'checklist', 'Competency Checklist App', 0, 'Generated by competency checklist application', 'script', now()),
(0, 'user.source_id', 'evaluation', 'Evaluation App', 0, 'Generated by competency checklist application', 'script', now())
;

SET @FEATURE_TYPE_ID = (SELECT feature_type_id FROM permission_feature_type WHERE feature_type_token = 'course');
INSERT INTO permission_role VALUES (0, 'healthprof', 'Healthcare Professional', @FEATURE_TYPE_ID, 1, 'script', now(), 'script', now());






