#!/usr/bin/perl

use HSDB4::SQLSelect;

# Example of the most simple SQLTable::new call; returns a SQLTable with
# table named "mytable", alias "mytable" and an empty fiel list.
my $tab = HSDB4::SQLTable->new ('mytable');

# More compliated: you can name parameters to SQLTable::new and specify an
# alias, and even fields, if you choose.
my $tab2 = HSDB4::SQLTable->new (-table => 'mytable',
				 -alias => 'mt2');


$tab->add_fields (qw(foo bar baz));
$tab2->add_fields (qw(bar baz qux));
my $cond = HSDB4::SQLCondition->new ('frank=bob', 'greg<12');
my $sel = HSDB4::SQLSelect->new (-tables => [$tab, $tab2, 'othertable'],
				 -conditions => $cond);
$sel->add_fields ('now()');
$sel->conditions()->add_or ('bob>greg');
$sel->order_by ('baz');
$sel->add_order_by ('bar');
$sel->get_table('mt2')->add_fields ('quxx');
$sel->get_table('othertable')->add_fields ('this', 'that', 'the_other');
$sel->add_fields ('othertable.another');
$sel->get_table('othertable')->alias('ot');
print join ("\n", $sel->all_fields);
print $sel->get_sql;
