#!/usr/bin/perl

use strict;

use HSDB4::SQLRow::Content;

$|=1;
my $path = '/tmp/index';

my $count = 0;
my $lastid;
my $doc = HSDB4::SQLRow::Content->new;
eval {
    foreach (1..10800) {
	$doc->lookup_key ($_);
	my $id = $lastid = $doc->primary_key or next;
	open HTML, ">$path/$id.html" or die "Could not create $path/$id.html";
	print HTML $doc->out_html_forindex;
	close HTML;
	$count++;
	print "Did $count...\n" if ($count % 100) == 0;
    }
};
print $@ if $@;
print "Got to $lastid before dying.";
1;
